import React from 'react';

function AimingText () {
    return(
        <div>
            <p className="GuideText">Let's talk about how you can improve your aim. First off, there isn't any magic trick to it. No sensitivity or crosshair is better than another. That is simply all user preference. If you want to improve your aim, you have dedicate yourself to it. I'll use the same analogy I used 3 years ago during my first guide. You don't workout once at the gym and suddenly wake up looking like Arnold Schwarzenegger from the Terminator. It's about consistentcy, it's about dedication. It's not about deathmaking once for 24 hours straight but deathmatching 30 or 60 minutes a day for a long time period. You'll have moments where you take strides and improve but you can easily go periods of time where you don't feel like you're improving. Same with working out, you might reach that personal goal bench or squat but be stuck at that PR for a while before breaking through it. If you seriously want to improve your aim, you have to willing to work day after day to improve it. That's the no bullshit truth to it.</p>
            <p className="GuideText">Let's now talk about some specific aim mechanics and some different ways you can improve your aim. We'll start off by talking about crosshair placement when it comes to pre-aiming specific angles. What I mean by this is knowing exactly where you want to place your crosshair when you peak an angle. If you're coming out ramp on mirage and fear someone is holding the top of stairs, if you're aiming more towards triple. You have to spend time just simply moving your crosshair accross the screen which in the meantime, you can easily be killed before you get a single shot off on the enemy. So using my example, what can you do to improve in this scenario? Spend time learning crosshair placement for common angles, learn how to pre-fire them effectively and be ready next time around. There is a lot of really well made maps on the steam workshop that are specifically made for you to learn angles. I've personally spent a fair amount of time using them in the past. Hell, it became something I regularly used before matches to warm up on a specific map. I strongly encourage you to spend time using these maps to learn common angles across all maps. I can say with confidence that these will help you.</p>
            <p className="GuideText">Let's now talk about some specific aim mechanics and some different ways you can improve your aim. We'll start off by talking about crosshair placement when it comes to pre-aiming specific angles. What I mean by this is knowing exactly where you want to place your crosshair when you peak an angle. If you're coming out ramp on mirage and fear someone is holding the top of stairs, if you're aiming more towards site. You have to spend time just simply moving your crosshair accross the screen which in the meantime, you can easily be killed before you get a single shot off on the enemy. So using my example, what can you do to improve in this scenario? Spend time learning crosshair placement for common angles, learn how to pre-fire them effectively and be ready next time around. There is a lot of really well made maps on the steam workshop that are specifically made for you to learn angles. I've personally spent a fair amount of time using them in the past. Hell, it became something I regularly used before matches to warm up on a specific map. I strongly encourage you to spend time using these maps to learn common angles across all maps. I can say with confidence that these will help you.</p>
        </div>
    )
}

export default AimingText;