import React from 'react';

function AimingText () {
    return(
        <div>

            <div className="GuideTextPara">
                <h5 className="GuideTextH5">Let's get one thing out of the way:</h5>
                <p className="GuideTextP">There isn't any magic trick to it. No sensitivity or crosshair is better than another. That is simply all user preference. If you want to improve your aim, you have dedicate yourself to it. I'll use the same analogy I used 3 years ago during my first guide. You don't workout once at the gym and suddenly wake up looking like Arnold Schwarzenegger from the Terminator. It's about consistentcy, it's about dedication. It's not about deathmaking once for 24 hours straight but deathmatching 30 or 60 minutes a day for a long time period. You'll have moments where you take strides and improve but you can easily go periods of time where you don't feel like you're improving. Same with working out, you might reach that personal goal bench or squat but be stuck at that PR for a while before breaking through it. If you seriously want to improve your aim, you have to willing to work day after day to improve it. That's the no bullshit truth to it.</p>
            </div>

            <div className="GuideTextPara">
                <h5 className="GuideTextH5">Crosshair Placement:</h5>
                <p className="GuideTextP">Let's now talk about some specific aim mechanics and some different ways you can improve your aim. We'll start off by talking about crosshair placement when it comes to pre-aiming specific angles. What I mean by this is knowing exactly where you want to place your crosshair when you peak an angle. If you're coming out ramp on mirage and fear someone is holding the top of stairs, if you're aiming more towards site. You have to spend time just simply moving your crosshair accross the screen which in the meantime, you can easily be killed before you get a single shot off on the enemy. So using my example, what can you do to improve in this scenario? Spend time learning crosshair placement for common angles, learn how to pre-fire them effectively and be ready next time around. There is a lot of really well made maps on the steam workshop that are specifically made for you to learn angles. I've personally spent a fair amount of time using them in the past. Hell, it became something I regularly used before matches to warm up on a specific map. I strongly encourage you to spend time using these maps to learn common angles across all maps. This will help you with your crosshair placement immensely by knowing the common angles to place your crosshair when peaking a specific angle.</p> 
            </div>

            <div className="GuideTextPara">
                <h5 className="GuideTextH5">Aimbots for DM:</h5>
                <p className="GuideTextP">One of the most commonly used methods for deathmatch is using offline aim bots for aim practice. If you haven't done something of this nature, go to the steam workshop and looking for Aim Botz made by Mr. Ulletical. With Aim Bots, you can practice specific types of aim mechanics. The most common aim mechanics I use personally is working on flicking/snapping onto bots heads, spray transfering, and killing as many bots as possible in a time period. The first is flicking/snapping onto people. What I do specifically is aim off the target then attempt to snap to the bots head then back to the original position with tapping. I'll sometimes place my crosshair towards down towards the ground and snap up or vice versa with straight highing and snapping low. I find this useful for moments where someone peaks you from an unexpected angle, when you have high ground and aiming down or below and someone peaks from on top. The second is spraying transfering. Simply put, I spray between bots. It's nothing crazy but having a good spray transfer can help you in a lot of situations. May it be getting 2 kills instead of one or just simplying causing damage on the second player. Whatever it may be, practicing and having a strong spray transfer is very useful. The third is a good combination of two I've already talked about. I'll attempt to kill as many bots in a 1, 2, 3 minute time period. I'll usually do this at the end. This is something I like to do in between games to keep warm.</p>
            </div>

            <div className="GuideTextPara">
                <h5 className="GuideTextH5">Deathmatch:</h5>
                <p className="GuideTextP">The other commonly used meth for practicing your aim is public deathmatch servers against other players. There are dozens of these servers you can join. Something I will say, I would personally focus on deathmatching on Chicago, Dallas and Denver servers rather than the server closest to you. Why you may ask? Because you're more than likely going to always be playing on those 3 servers. If you can get used to playing the ping for that server, it'll feel more comfortable once you start playing actual games. With that said, let's talk about some specific aim mechanics you can focus on practicing in these deathmatch servers. I'll first say that you should go into a DM with a specific goal in mind. This allows you to strive towards something. While DMing mindlessly is still a good thing simply because you're still practicing your aim. Having a specific goal can help you have that feeling you're reaching for something and that could help with the frustration/boredom that some feel deathmatching. I tend to focus on doing 2 main things for DM, first being spraying. With every engagement, I'll spray no matter the range. I'll never know when I might have to spray in a match, so if I have encountered that in a deathmatch, I at least have some feel for the spray for the engagement. The second would be simply tapping for all engagements. Something specific to work on for this would be to take your time having at the head rather than just shooting the moment i see an enemy.</p>
            </div>
        </div>
    )
}

export default AimingText;