import React from 'react';

function BeginnerGuideText() {
    return(
        <div>
            <div className="GuideTextPara">
                <h5>Beginner Guide:</h5>
                <p>This will be part 1 of a 4 part series where I will outline some specifics you should focus on learning, improving or getting into depending on roughly where your skill level is. Part 1 which is the beginner guide is going to be outlined for someone in the skill range from new to the gold nova ranks. All these ranks are people who are just learning and understanding aspects of the game. The intermediate guides are designed for people in the range of AK to the Global Range that hasn't yet began to start playing third party services such as FaceIt and ESEA. Experienced will be people who are in the Supreme/Global range who is getting into ESEA/FaceIt play. Advanced are players who are looking to get into League play on top of beginning to grind clubs/leaderboards such as ESEA A+ learboards/Rank G and Faceit FPLC/FPLC qualifiers.</p>
            </div>
            <div className="GuideTextPara">
                <h5>I'm new/just getting into Counter Strike, what should I focus on?</h5>
                <p>I would advise spending some time just learning each of the more common competitive maps. That being Mirage, Inferno, Dust2 and perhaps Train. These will be the most common maps you'll play early on. Main reason being that they're the simplest to learn in general. I advise to hop in an offline server or deathmatch just learning the map, getting used to positions on the maps and figuring out some angles you'll be fighting from. Another thing you can do to learn these maps would be to watch a professional map on it. While I don't necessarily advise copying exactly whats going on, you can simply look to see where fights are commonly happening between these teams. For a map like Dust2, a lot of the fights happen towards Long A, Catwalk, Mid doors and B site. You can then hop back into an offline server, practice these angles and just learn how to peek/pre-fire these spots.</p>
            </div>
            <div className="GuideTextPara">
                <h5>I'm new/just getting into Counter Strike, what should I focus on?(continued)</h5>
                <p>The other main thing I would focus on is learning the main two rifles. That being the M4A4/M4A1 and AK-47. If you're not an AWPer, you'll end up using these two rifles primarily accross your entire CS life. You will want to learn how to spray, how to tap and how to burst these rifles to the best of your abilities. It's a long long process that is never ending. 7+ years in and I'm still trying to improve day by day. I would personally advise going to the steam workshop and downloading a spray tutorial map from there. I personally use Mr Ulitical's Spray Training map but any map really works as long as the spray is accurate. I would incorporate this type of spray training into your regular aim training sessions. When you are there, you will also want to spend some type learning how to burst in 3, 5 or 10 bullets sets. Whatever feels the most comfortable, bursting will be a lot more effective in long range engagements. It'll be a more consistent way of winning engagements than would be spraying your entire clip.</p>
            </div>
            <div className="GuideTextPara">
                <h5>What are some other things I can do to play better at my level?</h5>
                <p>Basic Utility knowledge and usage will help you a lot. You do not need to know any extrodinaire smoke lineup but rather basic smokes can help a lot. Knowing how to smoke top middle on mirage or CT on Inferno are two basic smokes that you should know when playing. To the right of this text will be a picture of all the smokes you should know for each map. I would advise spending a good amount of time learning how to throw these smokes as they will 100% help you in a game to game basis. The next thing would be knowing how to throw basic flashes for yourself and for your teammates. The flash is such an underrated piece of utility at the lower ranks. Effective flashes for yourself or your teammates can get you or your teammate kills and sometimes single handily win rounds. The next piece of utility would be the molotov. These can be used in choke points to shut down rushes or stop hits for a short period of time that allows for your teammates to rotate/flank on CT or kill time on a retake on T side. You can also save that molotov on T side for the bomb as that can be thrown on the bomb forcing the opposing team to get off the defuse sometimes winning the round without even having to fight. The last piece of utility would be the grenade which you can use to get chunk damage on a team rushing a bombsite through a choke point or finish off a CT player hiding behind or around a position. Something to note and it is very important is that sometimes it is simply better to show have your gun out and focus on shooting the enemy rather than throwing utility, especially at this level. Don't be the person always dying with utility out. If an enemy could peek you, have your gun out and be ready to engage. That split second between throwing the nade and pulling your gun out could cost you your life. Though, knowing basic utility can and will help you. </p>
            </div>
            <div className="GuideTextPara">
                <h5>I'm struggling to rank up, whats the deal? I'm always top fragging by myself and my team sucks!</h5>
                <p>I'll break it to you now, this will always happen to some extent. My own personal advise here would be to either try to get your friends or reach out to groups to find people to play with. Playing with people you know and have played with will give you a better chance at winning. You can create basic strategies and chemistry with friends. You can use utility to support each other and simply work together on taking sites. If you're unable to do this, just continue to work on your own game. Deathmatch, continuously practice your aim. Attempt to play with people from matches you win. I can guarantee you this, if you continuous improve your own game. You will rank up. There isn't somebody out there dropping 50 bombs game after game stuck in Gold Nova for 7 years now, eventually you'll win games and rank up.</p>
            </div>
            <div className="GuideTextPara">
                <h5>Final Comments:</h5>
                <p>You're just beginning your Counter-Strike experience. Enjoy it, it's a fun addicting game that everyone is trying to improve at. The best players today are better than the best players last year, they're better than the players the year before. For over 20 years now players have been trying to get better and better at the game. If you put time and effort into this game, you will get better. Take your time learning some specifics outlined above, play as much as you want but don't blow your brains out playing this game. You will lose games you should win and win games you should lose. Overall, have fun at the end of the day.</p>
            </div>
        </div>
    )
}

export default BeginnerGuideText;