import React from 'react';

function DemosText() {
    return(
        <div>
            <div>
                <h5>Let's speak about the IGLs best friend.</h5>
                <p className="GuideTextPara">Using Demos to learn, adapt and improve is the key to any successful IGL. You can utilize Demos a vast majority of ways to improve. You can use it to help your teammates improve, your team and yourself all at once. It is in my opinion the most important tool to improving as an IGL. Throughout this guide, we'll speak of the many ways you can use a demo, what you should be looking for when you're watching a demo, what questions you should be asking yourself and some notes that I keep track of when watching a game back.</p>
            </div>
            <div>
                <h5>The importance of watching a demo.</h5>
                <p className="GuideTextPara">I'll speak about the importance of demos for anything who isn't fully aware. Watching a demo allows you to review all aspects of a game that you played. You're able to go back and see exactly what you did right and did wrong. This allows you to make adjustments in game accordingly. One of the main reasons why people tie demos to IGLs is that it allows for IGLs to review the gameplan they use, the strats they call, the execution of the strats and much more. Though, the demo can be useful to all types of players, not just IGLs. I highly advise watching demos to players struggling at any and all ranks. It can give you a vantage to why you might not be playing your game that doesn't necessarily come to you right away. If you want to read a full guide designed for all players on demos, you can head over to the individual improvement tab and select demos where you'll find a guide written for all players. This guide will be specifically be towards IGLs using demos.</p>
            </div>
            <div>
                <h5>Let's talk first about what you should look for from a strategy standpoint.</h5>
                <p className="GuideTextPara">So what I mean from that is that from a basic standpoint, is the strat or setup that you called for, is it the correct strategy for the situation? We can answer this by taking into account a few factors. Your economy, the opposing teams economy, game flow and previous round results. The first part is very basic in the sense that if my team has a good buy and the opposing team is saving, I do not want to do something crazy or call a strategy specifically for a gun round or anything risky on CT side that Vice versa, I want to call a strat that focuses on getting the bomb down or trying to take as many guns down as possible. The advantage of watching demos when it comes to the two prior points is that you can see how your team plays these rounds and how strong your ability to track economy is. If you see yourself losing anti-eco rounds often, taking a look back at the rounds and finding out why you're losing these rounds. May be a lack of awareness, over/under aggression or simply being too seperated and allowed too many individual fights.</p>
                <p className="GuideTextPara">Now let's get into the meat and potatoes which are the gun rounds. When you're watching a gun round, you want to look for two key factors. The first being gameflow and the second being previous round results. I define gameflow as the pace which the opposing team is playing at, the pace your team is best suited for and the pace of previous rounds. For previous round results, I look at the split between sites being hit/sites we're hitting, the success of sites being hit, how we're hitting(executing, contacting, rushing), the success of our sites being hit and how they're attacking them(executing, contacting, rushing). Now with all that said, you'll want to take a basic look at the strategy that you called. May it be to split A from connector, A ramp and Palace on Mirage. Or if you called to lean an aggressive setup towards connector with retake on A. Whatever the call may be, you want to review why you called this strategy or setup. If you can give a reason to why you're calling that, that is a good thing because you're attempting to use previous round results and gameflow into account when calling a strat or setup. Now let's say you can't list specific reasons why you called that strat or setup, you want to go back and look at the game flow and previous round results to see that if that strat or setup makes sense for the given round. By doing this, this can help you learn how to take account for these factors. The more you review, the more you play, the easier it will become to make those important calls based off of something rather than pure gut or instinct.</p>
            </div>
        </div>
    )
}

export default DemosText;

//Now let's get into the meat and potatoes which are the gun rounds. I take into account two main factors when calling a strat/setup. That being gameflow and previous round results. My definition of gameflow is taking into account the pace the opposing team is playing at, the pace your team is best suited for and the pace of previous rounds(if possible). Now for previous round results, I look at the split between sites being hit/sites we're hitting, the success of sites being hit, how we're hitting (executing, contacting, rushing), the success of our sites being hit and how they're hitting them(executing, contacting, rushing). I take that into account and base my strategy for the upcoming round off that. 

//The IGL's best friend. The tool that every great IGL must master. The key to improving as an IGL. Whatever you want to say about it, it's single handily the most important resource you can use in so many regards as an IGL. Within this part, I'll breakdown every part of Value's poorly designed system known as the Demo. Let's begin by explaining what it is. It allows you rewatch a game you've played. You can use it in a million ways to improve as a player. While it is one of the most useful tools, it also can be one of the most boring and painful parts of improving. No different than watching game film, you would rather be on the field making a play than watching it. 