import React from 'react';

function StrategiesText() {
    return(
        <p className="GuideText"> My own personal favorite part about being an IGL is creating a strat, encorporating it into my team and using it effectively in a league match. The satisfaction is one of the best for an IGL. Let's get into baby. I'm going to go over how I go about creating a strategy document first then speak about how I explain/teach the document to my team which allows them to learn it the easiest. 
        <br/>
        <br/>
        I'll usually start by breaking the document into different sections. Pistol rounds, Ecos, Anti-Ecos, Low buy rounds and Full buy rounds. After creating the sections, I'll list any strategies that fit the categories. This is where I begin to look for demos to watch. When I'm looking for demos to watch, I've been recently watching more MDL-Lower echelon of professional teams since I personally find what they're doing to be easier to implement into my own team. Trying to copycat what a team Astralis's level is doing is really difficult for an absolute boat load of reasons as they're doing everything at the highest levels individually. The lower echelon of professional teams are still developing and learning these skills. That's my own reasons but feel free to watch whomever you want. Now as I'm watching these demos, I'm accounting for the round and seeing what each team is doing. For example, I'll watch a round focusing and write down what the CT's are doing for an anti-eco round. Afterwards, I'll replay the round and look at the T's approach to the round is. By doing this, I've trouted down 2 strategies by watching just one round. Obviously I'm going to excluse rounds where one team is simplying pushing to die or a single player just pops off to win a round as that isn't a reliable strategy (Unless you have zywoo which then that is the strategy...consistently) When I'm actually writing down details to the strategy, I'm looking at multiple factors. The first being trying to determine why this strategy is being called by the team. Does it have to solely do with economy? Maybe it's a timing/information thing? Whatever it may, I want to figure this out so I can similarly looking for an identical situation to call the strat. I also want to look how the opposing team reacted to the strategy. If I can find a weakness and tweak the strategy to eliminate it, I'm a step ahead now. I do not want to simply just trot down the strategy and call it good. I want to spend time learning what is right and what is wrong with it. 
        <br/>
        <br/>
        Now that I've watched a few demos, written down a novel full of strategies and I'm preparing to show and teach my team the strategies. I immediately break it down. Just because I wrote down a couple dozen strats doesn't mean I should immediately incorporate a couple dozen strategies to my team on a map. I break it into sections. I want the easiest to learn strategies and defaults done first before I get into more detailed oriented strategies. If you make a teammate or few overwhelmed with information, they're going to forget or mix up strategies and it will take longer to get a map down. Simple is sometimes better, this is a scenario where it is without a doubt better. Break apart your document of strategies into easier to learn sections. Implement each section day by day or every couple days, whatever the teams pace is. Don't force it down your teams throat. 
        <br/>
        <br/>
        Something that I'm guilty of myself is that I sometimes refuse to adjust a strategy after a period of time. This can allow for teams to watch your demo and prepare a counter strat if you run a specific strategy. By simply changing a small detail every once in a while, different molly or smoke or maybe add/remove a lurker can keep the opposing team from simply counter stratting a strat. Never settle on a strategy, always look for ways to improve and expand on a strategy and make that a common thing you do with all strats on all maps. Fluidity is a great strength to have when it comes to designing strats. 
        </p>
    )
}

export default StrategiesText;